### ISSUE TITLE
Timeout error during histogram QC

### ISSUE THREAD

**Issue by B195515** [qwerty239qwe/scTenifoldpy#11]
Hi, thank you for creating this alternative to the R package! 
I'm having trouble finding how to disable the histogram or redirecting the output into a png/pdf during the qc step, as it's causing a Timeout error. 
Appreciate your help!

**Comment by qwerty239qwe** [comment]
Hello B195515,
Thanks for using this package. Could you update this package to 0.1.3 and add {"plot": False} to the qc_kws in scTenifoldNet?
For example,
`sc = scTenifoldNet(df_1, df_2, "X", "Y", qc_kws={"min_lib_size": 1, "plot": False}, nc_kws={"n_cpus": 1})`

Please let me know if this fix the issue. Thanks!

**Comment by nureenmz** [comment]
Hi, thanks for your reply! 

I managed to figure out that the issue was with Ray not being able to use multiple cores (nc step) in my institute's compute cluster for some unknown reason.
It works now on a different compute node, and I used the step-by-step run. Works great!

**Comment by qwerty239qwe** [comment]
Glad to hear that everything works now. I will close this issue now. Feel free to reopen it if the problem happens again.
